### ISSUE TITLE
FMLModType included in fabric jars

### ISSUE THREAD

**Issue by ThatGravyBoat** [EssentialGG/UniversalCraft#70]
The `FMLModType` manifest entry is included in fabric jars which causes issues with things like Sinytra Connector.

https://github.com/EssentialGG/UniversalCraft/blob/d0ab6220383c843c3e294d94671d96ed38f11ce2/build.gradle.kts#L30

In addition FMLModType is LIBRARY when in modern versions it should be GAMELIBRARY as LIBRARY is meant for plugin layers while GAMELIBRARY is meant for mods/code that references minecraft code in the game layer 
- Forge: https://github.com/MinecraftForge/ForgeSPI/blob/master/src/main/java/net/minecraftforge/forgespi/locating/IModFile.java#L141
- NeoForge: https://github.com/neoforged/FancyModLoader/blob/main/loader/src/main/java/net/neoforged/neoforgespi/locating/IModFile.java#L180

**Comment by Protoxy22** [comment]
Up, it's really important
We cannot use Elementa on Forge 1.20+ because of this issue
UniversalCraft doesn't have the permission to access minecraft module ...

**Comment by caoimhebyrne** [comment]
For reference, the accepted fix for this (#73) isn't ideal, as UniversalCraft does not work in a development environment. Libraries cannot be shaded/relocated in development, so we still need that `FMLModType`.

Building UniversalCraft with the following appended to the buildscript does the trick:
```kt
tasks.jar {
    if (platform.isModLauncher) {
        manifest {
            // `GAMELIBRARY` is required to access Minecraft classes from ModLauncher 9 and higher.
            val modType = if (platform.mcVersion >= 11700) "GAMELIBRARY" else "LIBRARY"
            attributes(mapOf("FMLModType" to modType))
        }
    }
}
```

I will *probably* open a PR for this once I figure out how (if?) we can get Vigilance working nicely with UniversalCraft in development environments too.

**Comment by Sychic** [comment]
For some additional context, `GAMELIBRARY` only exists from 1.17 onward (added in [876d798](https://github.com/MinecraftForge/ForgeSPI/commit/876d79858e20174ca52872e0aae89dfb396cf2c7) to forge spi with the earliest release being forgespi 5.0 with a backport to 4.x).

**Comment by caoimhebyrne** [comment]
Yeah, noticed that - hence why changing Vigilance and Elementa would be annoying. Will probably do some research and put some rambling in [Discord](https://discord.com/channels/864592657572560958/945075920664928276/1379546173295300608) until I have something useful to add for this 🙃
